/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as HonorsRouteImport } from './routes/honors'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const HonorsRoute = HonorsRouteImport.update({
  id: '/honors',
  path: '/honors',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/honors': typeof HonorsRoute
  '/people': typeof PeopleRoute
  '/projects': typeof ProjectsRoute
  '/publications': typeof PublicationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/honors': typeof HonorsRoute
  '/people': typeof PeopleRoute
  '/projects': typeof ProjectsRoute
  '/publications': typeof PublicationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/honors': typeof HonorsRoute
  '/people': typeof PeopleRoute
  '/projects': typeof ProjectsRoute
  '/publications': typeof PublicationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/honors'
    | '/people'
    | '/projects'
    | '/publications'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/honors' | '/people' | '/projects' | '/publications'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/honors'
    | '/people'
    | '/projects'
    | '/publications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HonorsRoute: typeof HonorsRoute
  PeopleRoute: typeof PeopleRoute
  ProjectsRoute: typeof ProjectsRoute
  PublicationsRoute: typeof PublicationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/honors': {
      id: '/honors'
      path: '/honors'
      fullPath: '/honors'
      preLoaderRoute: typeof HonorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HonorsRoute: HonorsRoute,
  PeopleRoute: PeopleRoute,
  ProjectsRoute: ProjectsRoute,
  PublicationsRoute: PublicationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
